version: '3.8'

services:
  app:
    build: .
    command: /app/scripts/start.sh
    ports:
      - "6000:6000"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_PATH=/data/app.db
    volumes:
      - ./data:/data
    depends_on:
      - redis

  worker:
    build: .
    command: python worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_PATH=/data/app.db
    volumes:
      - ./data:/data
    depends_on:
      - redis
      - app
    deploy:
      replicas: 2  # Run 2 worker containers

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

